#<<<SAPPER SECTION BEGIN REPLACE MAKEFILE-TEST>>>
test: build
	cd build/tests; \
	ctest --output-junit testResult.xml --rerun-failed --output-on-failure;	
#<<<SAPPER SECTION END REPLACE MAKEFILE-TEST>>>