# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.20.1'
- script: |
    echo machine github.com login seboste password $(GIT_SAPPER_TOKEN) > ~/.netrc
    go env -w GOPRIVATE=github.com/seboste/*
    go install github.com/seboste/sapper@latest
    sapper
  displayName: 'install sapper'
