# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.20.1'
- script: |
    echo machine github.com login seboste password $(GIT_SAPPER_TOKEN) > ~/.netrc
    export GOBIN=/usr/local/bin/
    go env -w GOPRIVATE=github.com/seboste/*
    go install github.com/seboste/sapper@latest
    sapper remote add current $PWD --insert=0
    sapper remote remove sapper-bricks
  displayName: 'install & configure sapper'
- script: |
    echo "##vso[task.setvariable variable=BRICK_NAME;]handler-httplib"    
    echo $(BRICK_NAME)
    echo $(Agent.TempDirectory)/$(BRICK_NAME)
    echo "##vso[task.setvariable variable=SERVICE_DIR;]$(Agent.TempDirectory)/$(BRICK_NAME)"    
    sapper service add $(SERVICE_DIR) -p VERSION=1.0.0
    sapper brick add $(BRICK_NAME) --service $(SERVICE_DIR)
    sapper service build $(SERVICE_DIR)    
  displayName: 'test http handler'
