# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: bricks
  type: object
  default:
    - name: handler-http
      parameters: >
        -p HOST='0.0.0.0' -p PORT=8080
      run_tests: false
      run_smoke_test: true
    - name: handler-grpc
      parameters: >
        -p HOST='0.0.0.0' -p PORT=50051
      run_tests: false
      run_smoke_test: true
    - name: repo-in-memory
      parameters: ""
      run_tests: false
      run_smoke_test: true
    - name: observability-structured-logging
      parameters: >
        -p STRUCTURED_LOG_FIELDS='{"level","message"}'
      run_tests: false
      run_smoke_test: true
    - name: testing-catch2
      parameters: ""
      run_tests: true
      run_smoke_test: true
    - name: security-openid
      parameters: >
        -p OPENID_DEFAULT_URL='https://www.example.com/.well-known/openid-configuration'
      run_tests: true
      run_smoke_test: false
    - name: security-jwt-auth
      parameters: >
        -p OPENID_DEFAULT_URL='https://www.example.com/.well-known/openid-configuration' -p JWT_AUTH_AUDIENCE='https://www.example.com' -p JWT_AUTH_REQUIRED_CLAIMS='{"scope"}'
      run_tests: true
      run_smoke_test: false
    - name: repo-postgres
      parameters: >
        -p POSTGRES_CONNECTION_STRING='postgres://postgres:my_password@localhost:5432'
      run_tests: true
      run_smoke_test: false
    - name: notifier-http
      parameters: >
        -p NOTIFIER_CONNECTION_STRING='http://localhost:8080' -p NOTIFIER_MAX_RETRY_COUNT=3 -p NOTIFIER_FIRST_RETRY_INTERVAL_MS=100
      run_tests: false
      run_smoke_test: true
    - name: deploy-docker
      parameters: >
        -p PORT='8080' -p DOCKER_BASE_IMAGE='ubuntu:latest'
      run_tests: false
      run_smoke_test: false
    - name: deploy-kubernetes
      parameters: >
        -p PORT='8080' -p DOCKER_BASE_IMAGE='ubuntu:latest' -p KUBERNETES_REPLICAS=3
      run_tests: false
      run_smoke_test: false
    - name: repo-google-cloud-storage
      parameters: >
        -p PORT='8080' -p CLOUD_STORAGE_BUCKET='sapper-test-bucket' -p GOOGLE_APPLICATION_CREDENTIALS='key.json'
      run_tests: false
      run_smoke_test: false
    - name: notifier-google-pubsub
      parameters: >
        -p GOOGLE_APPLICATION_CREDENTIALS='key.json' -p PUBSUB_TOPIC='my-topic' -p GOOGLE_PROJECT='my-project'
      run_tests: false
      run_smoke_test: false
steps:
- task: GoTool@0
  inputs:
    version: '1.20.1'
- script: |
    export GOBIN=/usr/local/bin/
    go env -w GOPRIVATE=github.com/seboste/*
    go install github.com/seboste/sapper@latest
    sapper remote add current $PWD --insert=0
    sapper remote remove sapper-bricks
  displayName: 'install & configure sapper'
- script: |
    pip install conan==1.60.1
    conan profile new default --detect
    conan profile update settings.compiler.libcxx=libstdc++11 default
  displayName: install conan
- ${{ each brick in parameters.bricks }}:
  - script: |
      mkdir -p $(Agent.TempDirectory)/services
      sapper service add $(Agent.TempDirectory)/services/${{ brick.name }}-service -p VERSION=1.0.0
      if [ $? -ne 0 ]; then
        exit 1
      fi
      sapper brick add ${{ brick.name }} --service $(Agent.TempDirectory)/services/${{ brick.name }}-service ${{ brick.parameters }}
      if [ $? -ne 0 ]; then
        exit 1
      fi
      sapper service build $(Agent.TempDirectory)/services/${{ brick.name }}-service
      if [ $? -ne 0 ]; then
        exit 1
      fi
    displayName: 'build ${{ brick.name }}-service'
    condition: always()
  - script: |
      mkdir -p $(Agent.TempDirectory)/build_logs/${{ brick.name }}-service
      mv /tmp/sapper_build_log_*.log $(Agent.TempDirectory)/build_logs/${{ brick.name }}-service || true
    displayName: 'copy build logs ${{ brick.name }}-service'
    condition: always()
  - script: |
      sapper service test $(Agent.TempDirectory)/services/${{ brick.name }}-service      
    displayName: 'test ${{ brick.name }}-service'
    condition: eq(${{ brick.run_tests }}, true)
  - script: |
      mkdir -p $(Agent.TempDirectory)/test_reports/${{ brick.name }}-service
      mv $(Agent.TempDirectory)/services/${{ brick.name }}-service/build/tests/test_report.xml $(Agent.TempDirectory)/test_reports/${{ brick.name }}-service/test_report.xml || true
    displayName: 'move test report ${{ brick.name }}-service'
    condition: eq(${{ brick.run_tests }}, true)
  - script: |      
      sapper service run --stop-after 5s $(Agent.TempDirectory)/services/${{ brick.name }}-service
    displayName: 'smoke test ${{ brick.name }}-service'
    condition: eq(${{ brick.run_smoke_test }}, true)
  - script: |
      rm -rf $(Agent.TempDirectory)/services/${{ brick.name }}-service/build/src
    displayName: 'cleanup ${{ brick.name }}-service'
    condition: always()
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/build_logs'
    artifactType: 'pipeline'
    artifactName: 'build_logs'
  displayName: 'publish build logs'
  condition: always()
- task: PublishTestResults@2
  condition: always()
  displayName: 'publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Agent.TempDirectory)/test_reports/**/test_report.xml'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/services'
    artifactType: 'pipeline'
    artifactName: 'services'
  displayName: 'publish services'
  condition: always()