# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: bricks
  type: object
  default:
    - handler-httplib

steps:
- task: GoTool@0
  inputs:
    version: '1.20.1'
- script: |
    echo machine github.com login seboste password $(GIT_SAPPER_TOKEN) > ~/.netrc
    export GOBIN=/usr/local/bin/
    go env -w GOPRIVATE=github.com/seboste/*
    go install github.com/seboste/sapper@latest
    sapper remote add current $PWD --insert=0
    sapper remote remove sapper-bricks
  displayName: 'install & configure sapper'
- script: |
    pip install conan
  displayName: install conan
- script: |
    git clone https://github.com/seboste/microservice-essentials.git $(Agent.TempDirectory)/mse
    conan create -s compiler.libcxx=libstdc++11 $(Agent.TempDirectory)/mse
  displayName: obtain microservices essentials lib
- ${{ each brick in parameters.bricks }}:
  - script: |
      mkdir -p $(Agent.TempDirectory)/services
      sapper service add $(Agent.TempDirectory)/services/${{ brick }} -p VERSION=1.0.0
      sapper brick add ${{ brick }} --service $(Agent.TempDirectory)/services/${{ brick }}
      sapper service build $(Agent.TempDirectory)/services/${{ brick }}      
    displayName: 'test ${{ brick }}'    
  - script: |
      mkdir -p $(Agent.TempDirectory)/build_logs/${{ brick }}
      mv /tmp/sapper_build_log_*.log $(Agent.TempDirectory)/build_logs/${{ brick }} || true
    displayName: 'copy build logs ${{ brick }}'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/build_logs'
    artifactType: 'pipeline'
    artifactName: 'build_logs'
  displayName: 'publish build logs'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/services'
    artifactType: 'pipeline'
    artifactName: 'services'
  displayName: 'publish services'