# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: bricks
  type: object
  default:
    - name: handler-httplib
      parameters: ""
    - name: handler-grpc
      parameters: ""
    - name: repo-in-memory
      parameters: ""
    - name: observability-structured-logging
      parameters: >
        -p STRUCTURED_LOG_FIELDS='{"level","message"}'
    - name: security-openid
      parameters: >
        -p OPENID_DEFAULT_URL='https://www.example.com/.well-known/openid-configuration'
    - name: security-jwt-auth
      parameters: >
        -p OPENID_DEFAULT_URL='https://www.example.com/.well-known/openid-configuration' -p JWT_AUTH_AUDIENCE='https://www.example.com' -p JWT_AUTH_REQUIRED_CLAIMS='{"scope"}'
    
steps:
- task: GoTool@0
  inputs:
    version: '1.20.1'
- script: |
    echo machine github.com login seboste password $(GIT_SAPPER_TOKEN) > ~/.netrc
    export GOBIN=/usr/local/bin/
    go env -w GOPRIVATE=github.com/seboste/*
    go install github.com/seboste/sapper@latest
    sapper remote add current $PWD --insert=0
    sapper remote remove sapper-bricks
  displayName: 'install & configure sapper'
- script: |
    pip install conan==1.59.0
    conan profile new default --detect
    conan profile update settings.compiler.libcxx=libstdc++11 default
  displayName: install conan
- script: |
    git clone https://github.com/seboste/microservice-essentials.git $(Agent.TempDirectory)/mse    
    conan create $(Agent.TempDirectory)/mse
  displayName: obtain microservices essentials lib
- ${{ each brick in parameters.bricks }}:
  - script: |
      mkdir -p $(Agent.TempDirectory)/services
      sapper service add $(Agent.TempDirectory)/services/${{ brick.name }}-service -p VERSION=1.0.0
      if [ $? -ne 0 ]; then
        exit 1
      fi
      sapper brick add ${{ brick.name }} --service $(Agent.TempDirectory)/services/${{ brick.name }}-service ${{ brick.parameters }}
      if [ $? -ne 0 ]; then
        exit 1
      fi
      sapper service build $(Agent.TempDirectory)/services/${{ brick.name }}-service
      if [ $? -ne 0 ]; then
        exit 1
      fi
      rm -rf $(Agent.TempDirectory)/services/${{ brick.name }}-service/build/src
    displayName: 'test ${{ brick.name }}-service'
  - script: |
      mkdir -p $(Agent.TempDirectory)/build_logs/${{ brick.name }}-service
      mv /tmp/sapper_build_log_*.log $(Agent.TempDirectory)/build_logs/${{ brick.name }}-service || true
    displayName: 'copy build logs ${{ brick.name }}-service'
    condition: always()
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/build_logs'
    artifactType: 'pipeline'
    artifactName: 'build_logs'
  displayName: 'publish build logs'
  condition: always()
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/services'
    artifactType: 'pipeline'
    artifactName: 'services'
  displayName: 'publish services'
  condition: always()