apiVersion: apps/v1
kind: Deployment
metadata:
  name: <<<NAME>>>-deployment
  labels:
    app: <<<NAME>>>
spec:
  replicas: <<<KUBERNETES_REPLICAS>>>
  selector:
    matchLabels:
      app: <<<NAME>>>
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: <<<NAME>>>
    spec:
      containers:
      - name: <<<NAME>>>
        image: <<<NAME>>>:latest
        ports:
        - containerPort: <<<PORT>>>
        imagePullPolicy: IfNotPresent #makes sure that the image can be pulled from the local registry
